<?php
require '../includes/auth.php';
require '../config/db_connect.php';
include '../includes/header.php';

if (strtolower($_SESSION['role']) !== 'admin') {
    header("Location: ../auth/login.php");
    exit();
}

$db = new Database();
$conn = $db->connect();
$teacherID = $_SESSION['userID'];

// KPI 1: Total Requests directed to this teacher
$totalStmt = $conn->prepare("
    SELECT COUNT(*) as total 
    FROM withdrawal_request 
    WHERE TeacherID = :teacherID
");
$totalStmt->execute([':teacherID' => $teacherID]);
$totalRequests = $totalStmt->fetch()['total'];

// KPI 2: Pending Requests
$pendingStmt = $conn->prepare("
    SELECT COUNT(*) as total 
    FROM withdrawal_request 
    WHERE TeacherID = :teacherID AND Status = 'Pending'
");
$pendingStmt->execute([':teacherID' => $teacherID]);
$pendingRequests = $pendingStmt->fetch()['total'];

// KPI 3: Approved Requests
$approvedStmt = $conn->prepare("
    SELECT COUNT(*) as total 
    FROM withdrawal_request 
    WHERE TeacherID = :teacherID AND Status = 'Approved'
");
$approvedStmt->execute([':teacherID' => $teacherID]);
$approvedRequests = $approvedStmt->fetch()['total'];

// KPI 4: Rejected Requests
$rejectedStmt = $conn->prepare("
    SELECT COUNT(*) as total 
    FROM withdrawal_request 
    WHERE TeacherID = :teacherID AND Status = 'Rejected'
");
$rejectedStmt->execute([':teacherID' => $teacherID]);
$rejectedRequests = $rejectedStmt->fetch()['total'];

// KPI 5: Total Students under this teacher
$studentsStmt = $conn->prepare("
    SELECT COUNT(*) as total 
    FROM user 
    WHERE Role = 'Student' AND TeacherID = :teacherID
");
$studentsStmt->execute([':teacherID' => $teacherID]);
$totalStudents = $studentsStmt->fetch()['total'];

// KPI 6: This Month's Requests
$monthlyStmt = $conn->prepare("
    SELECT COUNT(*) as total 
    FROM withdrawal_request 
    WHERE TeacherID = :teacherID 
    AND MONTH(RequestDate) = MONTH(CURRENT_DATE()) 
    AND YEAR(RequestDate) = YEAR(CURRENT_DATE())
");
$monthlyStmt->execute([':teacherID' => $teacherID]);
$monthlyRequests = $monthlyStmt->fetch()['total'];

// DATA FOR GRAPHS
// Monthly Requests for the last 6 months
$monthlyDataStmt = $conn->prepare("
    SELECT 
        DATE_FORMAT(RequestDate, '%Y-%m') as month,
        COUNT(*) as total
    FROM withdrawal_request
    WHERE TeacherID = :teacherID
    AND RequestDate >= DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH)
    GROUP BY DATE_FORMAT(RequestDate, '%Y-%m')
    ORDER BY month ASC
");
$monthlyDataStmt->execute([':teacherID' => $teacherID]);
$monthlyData = $monthlyDataStmt->fetchAll(PDO::FETCH_ASSOC);

// Approved vs Rejected by Month (last 6 months)
$statusMonthlyStmt = $conn->prepare("
    SELECT 
        DATE_FORMAT(RequestDate, '%Y-%m') as month,
        Status,
        COUNT(*) as total
    FROM withdrawal_request
    WHERE TeacherID = :teacherID
    AND RequestDate >= DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH)
    AND Status IN ('Approved', 'Rejected')
    GROUP BY DATE_FORMAT(RequestDate, '%Y-%m'), Status
    ORDER BY month ASC
");
$statusMonthlyStmt->execute([':teacherID' => $teacherID]);
$statusMonthlyData = $statusMonthlyStmt->fetchAll(PDO::FETCH_ASSOC);

// Process data for Chart.js
$months = [];
$monthlyTotals = [];
$approvedByMonth = [];
$rejectedByMonth = [];

// Get last 6 months
for ($i = 5; $i >= 0; $i--) {
    $month = date('Y-m', strtotime("-$i months"));
    $months[] = date('M Y', strtotime("-$i months"));
    $monthlyTotals[$month] = 0;
    $approvedByMonth[$month] = 0;
    $rejectedByMonth[$month] = 0;
}

// Fill in the data
foreach ($monthlyData as $data) {
    $monthlyTotals[$data['month']] = (int)$data['total'];
}

foreach ($statusMonthlyData as $data) {
    if ($data['Status'] == 'Approved') {
        $approvedByMonth[$data['month']] = (int)$data['total'];
    } elseif ($data['Status'] == 'Rejected') {
        $rejectedByMonth[$data['month']] = (int)$data['total'];
    }
}

// Convert to arrays for JavaScript
$monthlyTotalsArray = array_values($monthlyTotals);
$approvedByMonthArray = array_values($approvedByMonth);
$rejectedByMonthArray = array_values($rejectedByMonth);

// Recent Requests for table
$recentStmt = $conn->prepare("
    SELECT wr.RequestID, u.FullName, c.CourseName, wr.RequestDate, wr.Reason, wr.Status
    FROM withdrawal_request wr
    JOIN user u ON wr.UserID = u.UserID
    JOIN course c ON wr.CourseID = c.CourseID
    WHERE wr.TeacherID = :teacherID
    ORDER BY wr.RequestDate DESC
    LIMIT 5
");
$recentStmt->execute([':teacherID' => $teacherID]);
$recentRequests = $recentStmt->fetchAll(PDO::FETCH_ASSOC);
?>

<!-- Add Print Header (hidden on screen) -->
<div class="print-header">
    <h1>Course Withdrawal System - Dashboard Report</h1>
    <p>Generated by: <?= htmlspecialchars($_SESSION['fullName']) ?> | Date: <?= date('F d, Y') ?></p>
</div>

<div class="welcome-banner">
    <h2>Welcome back, <?= htmlspecialchars($_SESSION['fullName']) ?>!</h2>
    <p>Here's an overview of your withdrawal requests and activities.</p>
</div>

<!-- Print Button -->
<div style="margin-bottom: 20px;">
    <button onclick="window.print()" class="btn" style="background: linear-gradient(135deg, #3a506b 0%, #5bc0be 100%);">
        🖨️ Print Dashboard Report
    </button>
</div>

<!-- KPI Statistics Grid -->
<div class="stats-grid">
    <div class="stat-card">
        <h3>Total Requests</h3>
        <div class="stat-number"><?= $totalRequests ?></div>
        <div class="stat-label">All time</div>
    </div>
    
    <div class="stat-card">
        <h3>Pending</h3>
        <div class="stat-number"><?= $pendingRequests ?></div>
        <div class="stat-label">Awaiting review</div>
    </div>
    
    <div class="stat-card">
        <h3>Approved</h3>
        <div class="stat-number"><?= $approvedRequests ?></div>
        <div class="stat-label">This semester</div>
    </div>
    
    <div class="stat-card">
        <h3>Rejected</h3>
        <div class="stat-number"><?= $rejectedRequests ?></div>
        <div class="stat-label">This semester</div>
    </div>
    
    <div class="stat-card">
        <h3>My Students</h3>
        <div class="stat-number"><?= $totalStudents ?></div>
        <div class="stat-label">Total enrolled</div>
    </div>
    
    <div class="stat-card">
        <h3>This Month</h3>
        <div class="stat-number"><?= $monthlyRequests ?></div>
        <div class="stat-label">New requests</div>
    </div>
</div>

<!-- CHARTS SECTION with proper print containers -->
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 20px; margin-bottom: 30px;">
    
    <!-- Monthly Requests Chart -->
    <div class="card chart-container">
        <h3>Monthly Withdrawal Requests (Last 6 Months)</h3>
        <div style="position: relative; height: 300px;">
            <canvas id="monthlyRequestsChart"></canvas>
        </div>
    </div>
    
    <!-- Approved vs Rejected Chart -->
    <div class="card chart-container">
        <h3>Approved vs Rejected (Last 6 Months)</h3>
        <div style="position: relative; height: 300px;">
            <canvas id="approvedRejectedChart"></canvas>
        </div>
    </div>
    
</div>

<!-- Status Distribution Pie Chart -->
<div class="card chart-container" style="max-width: 500px; margin: 0 auto 30px;">
    <h3>Request Status Distribution</h3>
    <div style="position: relative; height: 300px;">
        <canvas id="statusPieChart"></canvas>
    </div>
</div>

<!-- Page break before table when printing -->
<div class="page-break-before"></div>

<!-- Recent Requests Table -->
<div class="card">
    <h2>Recent Withdrawal Requests</h2>
    <?php if ($recentRequests): ?>
        <table>
            <tr><th>Student</th><th>Course</th><th>Reason</th><th>Date</th><th>Status</th></tr>
            <?php foreach ($recentRequests as $r): ?>
                <tr>
                    <td><?= htmlspecialchars($r['FullName']) ?></td>
                    <td><?= htmlspecialchars($r['CourseName']) ?></td>
                    <td><?= htmlspecialchars($r['Reason']) ?></td>
                    <td><?= htmlspecialchars($r['RequestDate']) ?></td>
                    <td class="<?= strtolower($r['Status']) ?>"><?= htmlspecialchars($r['Status']) ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
        <br>
        <a href="review_requests.php" class="btn">View All Requests</a>
    <?php else: ?>
        <p>No requests yet.</p>
    <?php endif; ?>
</div>

<!-- Chart.js Library -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>

<script>
// Chart.js Configuration
const chartColors = {
    primary: '#5bc0be',
    success: '#6bcf7f',
    danger: '#ff7b7b',
    warning: '#ffd93d',
    secondary: '#9ad1d4',
    dark: '#1c2541'
};

// Set default font color for better print visibility
Chart.defaults.color = '#e0e6ed';

// 1. Monthly Requests Line Chart
const monthlyCtx = document.getElementById('monthlyRequestsChart').getContext('2d');
const monthlyChart = new Chart(monthlyCtx, {
    type: 'line',
    data: {
        labels: <?= json_encode($months) ?>,
        datasets: [{
            label: 'Total Requests',
            data: <?= json_encode($monthlyTotalsArray) ?>,
            borderColor: chartColors.primary,
            backgroundColor: 'rgba(91, 192, 190, 0.1)',
            borderWidth: 3,
            fill: true,
            tension: 0.4,
            pointRadius: 5,
            pointHoverRadius: 7
        }]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: {
                labels: { 
                    color: '#e0e6ed', 
                    font: { size: 14 }
                }
            }
        },
        scales: {
            y: {
                beginAtZero: true,
                ticks: { 
                    color: '#9ad1d4',
                    stepSize: 1
                },
                grid: { color: 'rgba(58, 80, 107, 0.3)' }
            },
            x: {
                ticks: { color: '#9ad1d4' },
                grid: { color: 'rgba(58, 80, 107, 0.3)' }
            }
        }
    }
});

// 2. Approved vs Rejected Bar Chart
const approvedRejectedCtx = document.getElementById('approvedRejectedChart').getContext('2d');
const approvedRejectedChart = new Chart(approvedRejectedCtx, {
    type: 'bar',
    data: {
        labels: <?= json_encode($months) ?>,
        datasets: [
            {
                label: 'Approved',
                data: <?= json_encode($approvedByMonthArray) ?>,
                backgroundColor: chartColors.success,
                borderColor: chartColors.success,
                borderWidth: 1
            },
            {
                label: 'Rejected',
                data: <?= json_encode($rejectedByMonthArray) ?>,
                backgroundColor: chartColors.danger,
                borderColor: chartColors.danger,
                borderWidth: 1
            }
        ]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: {
                labels: { 
                    color: '#e0e6ed', 
                    font: { size: 14 }
                }
            }
        },
        scales: {
            y: {
                beginAtZero: true,
                ticks: { 
                    color: '#9ad1d4',
                    stepSize: 1
                },
                grid: { color: 'rgba(58, 80, 107, 0.3)' }
            },
            x: {
                ticks: { color: '#9ad1d4' },
                grid: { color: 'rgba(58, 80, 107, 0.3)' }
            }
        }
    }
});

// 3. Status Distribution Pie Chart
const statusPieCtx = document.getElementById('statusPieChart').getContext('2d');
const statusPieChart = new Chart(statusPieCtx, {
    type: 'doughnut',
    data: {
        labels: ['Pending', 'Approved', 'Rejected'],
        datasets: [{
            data: [<?= $pendingRequests ?>, <?= $approvedRequests ?>, <?= $rejectedRequests ?>],
            backgroundColor: [
                chartColors.warning,
                chartColors.success,
                chartColors.danger
            ],
            borderColor: chartColors.dark,
            borderWidth: 2
        }]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: {
                position: 'bottom',
                labels: { 
                    color: '#e0e6ed', 
                    font: { size: 14 },
                    padding: 20
                }
            }
        }
    }
});

// Handle print - ensure charts render properly
window.addEventListener('beforeprint', () => {
    monthlyChart.resize();
    approvedRejectedChart.resize();
    statusPieChart.resize();
});
</script>

<?php include '../includes/footer.php'; ?>