<?php
require '../includes/auth.php';
require '../config/db_connect.php';
require '../includes/header.php';

if (strtolower($_SESSION['role']) !== 'admin') {
    header("Location: ../auth/login.php");
    exit();
}

$db = new Database();
$conn = $db->connect();
$teacherID = $_SESSION['userID'];

// Filter variables
$status_filter = isset($_GET['status']) ? $_GET['status'] : 'all';
$date_from = isset($_GET['date_from']) ? $_GET['date_from'] : '';
$date_to = isset($_GET['date_to']) ? $_GET['date_to'] : '';

// Build query
$query = "
    SELECT wr.RequestID, u.FullName as StudentName, c.CourseName, wr.RequestDate, wr.Reason, wr.Status
    FROM withdrawal_request wr
    JOIN user u ON wr.UserID = u.UserID
    JOIN course c ON wr.CourseID = c.CourseID
    WHERE wr.TeacherID = :teacherID
";

$params = [':teacherID' => $teacherID];

// Apply filters
if ($status_filter != 'all') {
    $query .= " AND wr.Status = :status";
    $params[':status'] = $status_filter;
}

if (!empty($date_from)) {
    $query .= " AND wr.RequestDate >= :date_from";
    $params[':date_from'] = $date_from;
}

if (!empty($date_to)) {
    $query .= " AND wr.RequestDate <= :date_to";
    $params[':date_to'] = $date_to;
}

$query .= " ORDER BY wr.RequestDate DESC";

$stmt = $conn->prepare($query);
$stmt->execute($params);
$reports = $stmt->fetchAll(PDO::FETCH_ASSOC);
?>

<!-- Print Header -->
<div class="print-header">
    <h1>Course Withdrawal System - Reports</h1>
    <p>Generated by: <?= htmlspecialchars($_SESSION['fullName']) ?> | Date: <?= date('F d, Y') ?></p>
</div>

<div class="card">
    <h2>Withdrawal Requests Report</h2>
    
    <!-- Filter Form -->
    <form method="GET" style="margin-bottom: 20px; padding: 20px; background: #0f1a35; border-radius: 8px;">
        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px;">
            <div>
                <label>Status:</label>
                <select name="status">
                    <option value="all" <?= $status_filter == 'all' ? 'selected' : '' ?>>All Status</option>
                    <option value="Pending" <?= $status_filter == 'Pending' ? 'selected' : '' ?>>Pending</option>
                    <option value="Approved" <?= $status_filter == 'Approved' ? 'selected' : '' ?>>Approved</option>
                    <option value="Rejected" <?= $status_filter == 'Rejected' ? 'selected' : '' ?>>Rejected</option>
                </select>
            </div>
            
            <div>
                <label>Date From:</label>
                <input type="date" name="date_from" value="<?= htmlspecialchars($date_from) ?>">
            </div>
            
            <div>
                <label>Date To:</label>
                <input type="date" name="date_to" value="<?= htmlspecialchars($date_to) ?>">
            </div>
            
            <div style="display: flex; align-items: flex-end; gap: 10px;">
                <button type="submit" class="btn">Filter</button>
                <a href="reports.php" class="btn" style="background: #3a506b;">Reset</a>
            </div>
        </div>
    </form>

    <!-- Summary Stats -->
    <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 15px; margin-bottom: 20px;">
        <div style="background: #0f1a35; padding: 15px; border-radius: 8px; text-align: center;">
            <div style="font-size: 24px; color: #5bc0be; font-weight: bold;"><?= count($reports) ?></div>
            <div style="color: #9ad1d4; font-size: 12px;">Total Records</div>
        </div>
        
        <div style="background: #0f1a35; padding: 15px; border-radius: 8px; text-align: center;">
            <div style="font-size: 24px; color: #ffd93d; font-weight: bold;">
                <?= count(array_filter($reports, fn($r) => $r['Status'] == 'Pending')) ?>
            </div>
            <div style="color: #9ad1d4; font-size: 12px;">Pending</div>
        </div>
        
        <div style="background: #0f1a35; padding: 15px; border-radius: 8px; text-align: center;">
            <div style="font-size: 24px; color: #6bcf7f; font-weight: bold;">
                <?= count(array_filter($reports, fn($r) => $r['Status'] == 'Approved')) ?>
            </div>
            <div style="color: #9ad1d4; font-size: 12px;">Approved</div>
        </div>
        
        <div style="background: #0f1a35; padding: 15px; border-radius: 8px; text-align: center;">
            <div style="font-size: 24px; color: #ff7b7b; font-weight: bold;">
                <?= count(array_filter($reports, fn($r) => $r['Status'] == 'Rejected')) ?>
            </div>
            <div style="color: #9ad1d4; font-size: 12px;">Rejected</div>
        </div>
    </div>

    <!-- Export/Print Buttons -->
    <div style="margin-bottom: 20px;">
        <button onclick="window.print()" class="btn">🖨️ Print Report</button>
        <a href="export_report.php?<?= http_build_query($_GET) ?>" class="btn" style="background: #4caf50;">📥 Export to CSV</a>
    </div>

    <!-- Report Table -->
    <?php if ($reports): ?>
        <table class="styled-table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Student Name</th>
                    <th>Course</th>
                    <th>Request Date</th>
                    <th>Reason</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reports as $r): ?>
                    <tr>
                        <td><?= $r['RequestID'] ?></td>
                        <td><?= htmlspecialchars($r['StudentName']) ?></td>
                        <td><?= htmlspecialchars($r['CourseName']) ?></td>
                        <td><?= htmlspecialchars($r['RequestDate']) ?></td>
                        <td><?= htmlspecialchars($r['Reason']) ?></td>
                        <td class="<?= strtolower($r['Status']) ?>"><?= htmlspecialchars($r['Status']) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p>No records found for the selected criteria.</p>
    <?php endif; ?>
</div>

<?php require '../includes/footer.php'; ?>